# Generated by Django 3.1.7 on 2021-07-18 12:28

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='YTVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(blank=True, null=True, verbose_name='start')),
                ('end', models.DateTimeField(blank=True, null=True, verbose_name='end')),
                ('video_id', models.CharField(help_text='YouTube video id', max_length=255, null=True, unique=True)),
                ('title', models.CharField(help_text="The video's title. The property value has a maximum length of 100 characters and may contain all valid UTF-8 characters except < and >.", max_length=100)),
                ('description', models.TextField(blank=True, help_text="The video's description. The property value has a maximum length of 5000 bytes and may contain all valid UTF-8 characters except < and >.")),
                ('tags', models.CharField(blank=True, help_text='Comma seperated tags', max_length=255)),
                ('category_id', models.SmallIntegerField(choices=[(22, 'People and Blog')], default=22, help_text='The YouTube video category associated with the video.You must set a value for this property if you call the videos.update method and are updating the snippet part of a video resource.')),
                ('privacy_status', models.CharField(choices=[('private', 'Private'), ('unlisted', 'Unlisted'), ('public', 'Public')], default='private', help_text="The video's privacy status.", max_length=10)),
                ('publish_at', models.DateTimeField(default=datetime.datetime(2021, 8, 2, 12, 28, 11, 748158), help_text='The date and time when the video is scheduled to publish. It can be set only if the privacy status of the video is private. The value is specified in ISO 8601 format.')),
                ('embeddable', models.BooleanField(default=True, help_text='This value indicates whether the video can be embedded on another website.')),
                ('made_for_kids', models.BooleanField(default=False, help_text="This value indicates whether the video is designated as child-directed, and it contains the current 'made for kids' status of the video.")),
                ('notify_subscribers', models.BooleanField(default=False, help_text="The notifySubscribers parameter indicates whether YouTube should send a notification about the new video to users who subscribe to the video's channel. A parameter value of True indicates that subscribers will be notified of newly uploaded videos.")),
                ('youtube_url', models.URLField(blank=True, max_length=255, null=True)),
                ('file_on_server', models.FileField(help_text='Temporary file on server for                                               using in `direct upload` from                                               your server to youtube', null=True, upload_to='youtube/videos')),
                ('user', models.ForeignKey(help_text='User who uploaded video', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
