# Generated by Django 3.1.7 on 2021-07-18 12:34

import datetime
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ytvideo',
            name='end',
        ),
        migrations.RemoveField(
            model_name='ytvideo',
            name='start',
        ),
        migrations.AddField(
            model_name='ytvideo',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='ytvideo',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='ytvideo',
            name='publish_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 2, 12, 34, 28, 454884), help_text='The date and time when the video is scheduled to publish. It can be set only if the privacy status of the video is private. The value is specified in ISO 8601 format.'),
        ),
    ]
